feat(form-restoration): Form restoration now works
dotswan/filament-map-picker pull request #59
Opened 2024-12-04 14:47 UTC by artumi-richard

When you navigate away from a page and then return to it there is a "form restoration" process done by the browser. It puts values back as they were, by filling in the <select>'s and <input>'s (though not <input type="hidden">) with their old values.

By using this fact I've created a mechanism where the map saves it's lat, lng and zoom levels in a invisible <input>, and using the pageshow event to utilize this data after a navigation.

There is also work on problem that the center of the map has been used instead of marker position which is what #57 is about. 

The testing process for Form Restoration is that you go to a map, click on it, navigate away and then back to that page. Most of the fields will work but this map did not. 

As part of this I've also checked that this map can work multiple times on a single filament form.

2024-12-18 08:41 UTC, mohaphez requested changes
Great job @artumi-richard 

Thank you so much for your attention and cooperation in resolving this issue.

I’ve added a few comments to highlight points that could improve the organization and clarity of the code.

I would greatly appreciate it if you could review these suggestions and apply the changes if they align with your approach. Once that’s done, we can proceed with applying the new version.

2024-12-18 08:41 UTC, mohaphez commented on resources/js/index.js
> +            setFormRestorationState: function (coords,zoom ) {
Wouldn't be better and clear if we write like this ?

```js
setFormRestorationState: function(coords = null, zoom = null) {

    coords = coords || this.getFormRestorationState() || this.getCoordinates();

    if (this.map) {
        coords.zoom = zoom ?? this.map.getZoom();
    }

    this.formRestorationHiddenInput.value = JSON.stringify(coords);
},

```

2024-12-18 08:41 UTC, mohaphez commented on resources/js/index.js
> +                        if(!config.clickable)
Please refactor it just for make it clearer and more concise

```js
this.map.on('load', () => {
    setTimeout(() => this.map.invalidateSize(true), 0);
    
    if (config.showMarker && !config.clickable) {
        this.marker.setLatLng(this.map.getCenter());
    }
});
```

2024-12-18 08:41 UTC, mohaphez commented on resources/js/index.js
> +                if(config.clickable && !this.marker)
Please refactor it just for make it clearer and more concise

```js

setMarkerRange: function() {

    if ((config.clickable && !this.marker) || !this.rangeSelectField) {
        return;
    }

    const distance = parseInt(this.rangeSelectField.value || 0);
    const coordinates = this.getCoordinates();
    const circleStyle = {
        color: 'blue',
        fillColor: '#f03',
        fillOpacity: 0.5,
        radius: distance
    };
    
    if (this.rangeCircle) {
        this.rangeCircle
            .setLatLng(coordinates)
            .setRadius(distance);
        return;
    }
    
    this.rangeCircle = LF.circle(coordinates, circleStyle).addTo(this.map);
},

```

2024-12-29 19:13 UTC, merged

2025-01-06 11:20 UTC, artumi-richard commented
Yes. I will do this in the next week or so.

2025-01-06 11:24 UTC, artumi-richard commented
It looks like we now have this thanks to #62